use healthcare;
select * from healthcare;

-- 1. Retrieve the names of all patients in the database. 
select name from healthcare;

-- 2. List the unique medical conditions present in the dataset
select distinct medical_condition from healthcare;

-- 3. Find the total number of doctors in the healthcare system.
select count(doctor) from healthcare;

-- 4. Retrieve the details of all female patients.
select * from healthcare where gender='female';

-- 5. what is the average age of patients in the database.
select avg(age) from healthcare;

-- 6. Identify the patients who have more than one medical condition.
select Name from healthcare group by  Name having COUNT(DISTINCT medical_condition) > 1;

-- 7. List the names of all doctors.
select doctor from healthcare;

-- 8.Identify the most common medical condition among patients.
select medical_condition, COUNT(*) AS condition_count from healthcare group by  medical_condition order by condition_count desc LIMIT 1;

-- 9.Find the patients who are older than 60 years and have diabetes. 
select name,medical_condition from healthcare where age < 60 and medical_condition='Diabetes';

-- 10.Calculate the total revenue generated by the healthcare system.
select sum(Billing_Amount) as revenu from healthcare;

-- 11.Find the doctor with the oldest patient.
select doctor,name,age from healthcare where Age = (select max(Age) from healthcare);

-- 13.Give the names of patients whose name starts with A.
select name from healthcare where name like 'A%';

-- 14.How many male and female patients are there in dataset.
select gender,count(gender) from healthcare group by gender;

-- 15.how many patients are normal. 
select name,test_results from healthcare where test_results ='normal';

-- 16.how many patients are abnormal or Inconclusive.
select count(*) as number_of_patients from healthcare where test_results in ('Abnormal', 'Inconclusive');

-- 17.how many patients of blood group AB+ are there of age above 52.
select count(*) as number_of_patients from healthcare where Blood_Type = 'AB+' and Age > 52;

-- 18. how many patients have paid the bill above 24890. 
select count(*) as number_of_patients from healthcare where Billing_Amount > 24890;

-- 19. what are the names of patients having Asthma.
select name from healthcare where Medical_Condition='Asthma';

-- 20. how many patients have cancer.
select count(*) as number_of_patients from healthcare where medical_condition='cancer';

-- 21. what are the names and blood groups of patients admitted to room no. 292.
select name,blood_type from healthcare where Room_Number=292;

-- 22. how many males have Arthritis
select count(gender) from healthcare where gender='male' and medical_condition='Arthritis';

-- 23. How many patients were admitted to Harris and Sons hospital.
select count(*) as number_of_patients from healthcare where Hospital = 'Harris and Sons';

-- 24. what are the names of patients whose Insurance Provider are Cigna.
select name,Insurance_Provider from healthcare where Insurance_Provider='cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select distinct medical_condition from healthcare where age > (select avg(age) from healthcare);